version: 2
updates:
  - package-ecosystem: docker
    target-branch: "4.x" # This line should be deleted prior to the v4.0.0 release
    directory: /
    assignees:
      - "atkrad"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    target-branch: "4.x" # This line should be deleted prior to the v4.0.0 release
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "atkrad"
    labels:
      - "dependencies"
    groups:
      testcontainers:
        patterns:
          - github.com/testcontainers/*

  - package-ecosystem: "github-actions"
    target-branch: "4.x" # This line should be deleted prior to the v4.0.0 release
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "atkrad"
    labels:
      - "actions"
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
